### ISSUE TITLE
Adding various microphone configurations

### ISSUE THREAD

**Issue by sreeharshaparuchur1** [facebookresearch/rlr-audio-propagation#14]
Hi,

As mentioned in the [AUDIO.md](https://github.com/facebookresearch/habitat-sim/blob/main/docs/AUDIO.md#channel-layout) documentation, this library supports a variety of sensor types. However, when I try to add a sensor type other than Binaural or Ambisonics, say Quad, I get the following error:

```
line 134, in add_acoustic_config
    audio_sensor_spec.channelLayout.type = habitat_sim.sensor.RLRAudioPropagationChannelLayoutType.Quad
AttributeError: type object 'habitat_sim._ext.habitat_sim_bindings.RLRAudioProp' has no attribute 'Quad'
```

I am using the process to add a sensor that is followed in this [example notebook](https://github.com/facebookresearch/sound-spaces/blob/main/examples/soundspaces2_quick_tutorial.ipynb) having encountered [this issue](https://github.com/facebookresearch/rlr-audio-propagation/issues/13) a surfeit number of times.

Kindly let me know if the functionality is not supported yet and by when it will be rolled out or if I am making a mistake.

Thank you.

**Comment by carlschisslerfb** [comment]
The types other than Binaural, Mono, or Ambisonics have been removed because they were never implemented internally. It seems like the documentation that is in habitat-sim was not updated to reflect the changes to the API.

Refer to the python bindings of the audio sensor to see the most recent API, which indeed does not support the missing sensor types.
https://github.com/facebookresearch/habitat-sim/blob/RLRAudioPropagationUpdate/src/esp/bindings/SensorBindings.cpp#L357

It's unlikely that the missing sensor types will be implemented, because they do not correspond to real-world microphone configurations. They refer to generic surround-sound formats which are not applicable in the context of realistic spatial microphones. There are 3 methods which I would recommend to produce output for an arbitrary microphone configuration:
- Best would be if you have a measured array transfer function (ATF) for the microphones in AES SOFA format. This can be loaded using the same API as loading custom HRTF, and can be used in combination with the Binaural sensor type. In other words, Binaural can have more than 2 channels to represent multiple microphone arrays. This will reproduce exactly the signal received by the microphones with direction-dependent filtering.
- Otherwise, I would use an Ambisonic sensor type with the maximum number of channels (36, or 5th order), then decode the ambisonic signals to whatever arbitrary channels you want.
- Finally, you could use multiple mono sensors to replicate a multi-microphone system, but I'm not sure how well this will work. It would require running the simulation multiple times, and that may not be deterministic.
